#include "WorkbenchGameMode.h"
#include "KitParameters.h"
#include "KitPresetStore.h"
#include "KitBindings.h"
#include "KitParameterEditor.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Modules/ModuleManager.h"
#include "Engine/Engine.h"
#include "Engine/GameViewportClient.h"
#include "Engine/Texture2D.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/KismetRenderingLibrary.h"
#include "Widgets/SLeafWidget.h"
#include "Widgets/SWindow.h"
#include "Framework/Application/SlateApplication.h"
#include "UObject/StrongObjectPtr.h"
#include "Misc/ConfigCacheIni.h"
#include "Misc/FileHelper.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformApplicationMisc.h"
#include "UnrealClient.h"
IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl,KoaliticWorkbench,"KoaliticWorkbench");
namespace KW {
void SetInt(FConfigFile& C,const TCHAR* Section,const TCHAR* Key,int V){C.SetString(Section,Key,*FString::FromInt(V));}
struct Hit {int Id;FSlateRect Rect;};
class SWorkbench final:public SLeafWidget {
public:
 SLATE_BEGIN_ARGS(SWorkbench){} SLATE_ARGUMENT(UWorld*,World) SLATE_END_ARGS()
 void Construct(const FArguments& Args){World=Args._World;SetCanTick(true);ForceVolatile(true);SetCursor(EMouseCursor::Default);Portraits[0]=LoadImage(TEXT("PortraitSource.png"));Portraits[0].SetUVRegion(FBox2f({170.f/2048,151.f/726},{583.f/2048,546.f/726}));Portraits[1]=LoadImage(TEXT("PortraitAlternateSource.png"));Portraits[1].SetUVRegion(FBox2f({524.f/1672,257.f/941},{722.f/1672,444.f/941}));DataDir=FString(FPlatformProcess::UserSettingsDir())/TEXT("KOALITIC/WorkbenchV03");Verify=FParse::Param(FCommandLine::Get(),TEXT("WorkbenchVerify"));QA=FParse::Param(FCommandLine::Get(),TEXT("QAControl"));FParse::Value(FCommandLine::Get(),TEXT("Evidence="),Evidence);if(Evidence.IsEmpty())Evidence=FPaths::ProjectSavedDir()/TEXT("Verification");PersistenceRead=FParse::Param(FCommandLine::Get(),TEXT("PersistenceRead"));if(Verify||PersistenceRead)DataDir/=TEXT("VerificationKit");IFileManager::Get().MakeDirectory(*DataDir,true);Load();LoadKit();SeedKit();if(auto* Material=LoadObject<UMaterialInterface>(nullptr,TEXT("/Game/InterfaceMaterials/M_ProfileGlass.M_ProfileGlass"))){GlassMaterial.Reset(UMaterialInstanceDynamic::Create(Material,nullptr));GlassBrush.SetResourceObject(GlassMaterial.Get());GlassBrush.DrawAs=ESlateBrushDrawType::Image;}if(Verify){D=ProfileData();P=Presentation();Shared=Presentation();State=ProfileState();for(int I=0;I<ParamCount;I++)Overrides[I]=false;}K.Time=0;K.From=0;Started=FPlatformTime::Seconds();UE_LOG(LogTemp,Display,TEXT("WORKBENCH_READY Unreal 5.8 layered runtime; portrait assets=%d/%d; storage=%s"),Portraits[0].GetResourceObject()!=nullptr,Portraits[1].GetResourceObject()!=nullptr,*DataDir);}
 FVector2D ComputeDesiredSize(float)const override{return {1920,1080};}bool SupportsKeyboardFocus()const override{return true;}
 FSlateBrush LoadImage(const FString& File){FSlateBrush B;UTexture2D* T=UKismetRenderingLibrary::ImportFileAsTexture2D(World.Get(),FPaths::ProjectContentDir()/TEXT("Interface")/File);if(T){T->Filter=TF_Bilinear;Textures.Emplace(T);B.SetResourceObject(T);B.ImageSize=FVector2D(T->GetSizeX(),T->GetSizeY());B.DrawAs=ESlateBrushDrawType::Image;}return B;}
 void Tick(const FGeometry& G,double Now,float Dt)override{ResolveKit();if(DeferredAction>=0&&--DeferredFrames<=0){int Action=DeferredAction;DeferredAction=-1;Activate(Action);}if(K.Playing)K.Time+=FMath::Min(Dt,.1f);SeekEnd=FMath::Max(SeekEnd,FMath::Max(12.f,FMath::CeilToFloat(K.Time/6)*6));RealTime=FPlatformTime::Seconds()-Started;if(!TitleSet&&RealTime>.5f&&GEngine&&GEngine->GameViewport){if(auto Window=GEngine->GameViewport->GetWindow()){Window->SetTitle(FText::FromString(TEXT("KOALITIC | UI Workbench 0.3")));TitleSet=true;}}if(RealTime>3){FrameSum+=Dt;FrameCount++;MaxFrame=FMath::Max(MaxFrame,Dt);}if(State.AutoCollapse&&!State.Pinned&&!State.Hover)State.SetCompact(true,K.Time,!K.Playing);if(Verify)VerifyTick();if(PersistenceRead&&RealTime>3){Check(D.Name==TEXT("KIT VERIFY")&&D.XP==4990&&P.Entrance==1&&P.Exit==1,TEXT("Shared assignments survive packaged restart"));Check(Overrides[7]&&FMath::IsNearlyEqual(P.AmbientStrength,.33f)&&FMath::IsNearlyEqual(Shared.AmbientStrength,.81f),TEXT("Per-value override and shared preset survive packaged restart"));IFileManager::Get().MakeDirectory(*Evidence,true);FFileHelper::SaveStringToFile(Checks,*(Evidence/TEXT("restart-results.txt")));FGenericPlatformMisc::RequestExit(false);PersistenceRead=false;}if(QA&&RealTime-LastQA>.2f){LastQA=RealTime;FString Cmd;FString Path=Evidence/TEXT("command.txt");if(FFileHelper::LoadFileToString(Cmd,*Path)&&!Cmd.IsEmpty()){FFileHelper::SaveStringToFile(TEXT(""),*Path);ExecuteQA(Cmd);}}UpdateMaterial();Invalidate(EInvalidateWidgetReason::Paint);}
 void BeginTransition(bool Exit){auto V=Evaluate(D,PreviewValues(),K,Events);K.From=(!Exit&&V.Reveal>.99f)?0:V.Reveal;K.Transition=K.Time;K.Exiting=Exit;K.Playing=true;}
 void AddXP(int Amount){Events.RemoveAll([&](const Reward& R){return R.Time>K.Time;});Events.Add({K.Time,Amount});K.Playing=true;Notice=FString::Printf(TEXT("Preview event #%d  /  +%d XP"),Events.Num(),Amount);UE_LOG(LogTemp,Display,TEXT("REWARD event=%d amount=%d time=%.3f"),Events.Num(),Amount,K.Time);}
 void WriteConfig(FConfigFile& C){WriteKitLinks(C);C.SetString(TEXT("Profile"),TEXT("Name"),*D.Name);SetInt(C,TEXT("Profile"),TEXT("Level"),D.Level);SetInt(C,TEXT("Profile"),TEXT("XP"),D.XP);SetInt(C,TEXT("Profile"),TEXT("Threshold"),D.MaxXP);SetInt(C,TEXT("Style"),TEXT("Portrait"),P.Portrait);for(int I=0;I<8;I++)C.SetBool(TEXT("Layers"),*FString::FromInt(I),P.Layers[I]);C.SetBool(TEXT("State"),TEXT("Compact"),State.Compact);C.SetBool(TEXT("State"),TEXT("Pinned"),State.Pinned);C.SetBool(TEXT("State"),TEXT("AutoCollapse"),State.AutoCollapse);}
 void ReadMotion(FConfigFile& C,const TCHAR* Sec){C.GetInt(Sec,TEXT("Entrance"),P.Entrance);C.GetInt(Sec,TEXT("Exit"),P.Exit);C.GetInt(Sec,TEXT("Direction"),P.Direction);C.GetFloat(Sec,TEXT("Duration"),P.Duration);C.GetFloat(Sec,TEXT("ExitDuration"),P.ExitDuration);C.GetFloat(Sec,TEXT("Stagger"),P.Stagger);P.Entrance=FMath::Clamp(P.Entrance,0,4);P.Exit=FMath::Clamp(P.Exit,0,4);P.Duration=FMath::Clamp(P.Duration,.15f,6.f);P.ExitDuration=FMath::Clamp(P.ExitDuration,.15f,6.f);P.Stagger=FMath::Clamp(P.Stagger,0.f,.35f);}
 void Save(){FConfigFile C;WriteConfig(C);Notice=C.Write(DataDir/TEXT("Presentation.ini"))?TEXT("Presentation saved  /  synthetic rewards excluded"):TEXT("SAVE FAILED: cannot write local settings");}
 void Load(){FConfigFile C;C.Read(DataDir/TEXT("Presentation.ini"));if(!C.Contains(TEXT("Profile"))){Notice=TEXT("Fresh presentation  /  local workspace");return;}C.GetString(TEXT("Profile"),TEXT("Name"),D.Name);C.GetInt(TEXT("Profile"),TEXT("Level"),D.Level);C.GetInt(TEXT("Profile"),TEXT("XP"),D.XP);C.GetInt(TEXT("Profile"),TEXT("Threshold"),D.MaxXP);D.MaxXP=FMath::Clamp(D.MaxXP,100,999999);D.XP=FMath::Clamp(D.XP,0,D.MaxXP-1);D.Level=FMath::Clamp(D.Level,1,999);D.Name=D.Name.Left(18);C.GetInt(TEXT("Style"),TEXT("Portrait"),P.Portrait);P.Portrait=FMath::Clamp(P.Portrait,0,1);C.GetInt(TEXT("Style"),TEXT("Accent"),P.Accent);C.GetInt(TEXT("Style"),TEXT("Ambient"),P.Ambient);C.GetFloat(TEXT("Style"),TEXT("Glow"),P.Glow);C.GetFloat(TEXT("Style"),TEXT("Glitch"),P.Glitch);C.GetFloat(TEXT("Style"),TEXT("Frequency"),P.Frequency);C.GetFloat(TEXT("Style"),TEXT("AmbientStrength"),P.AmbientStrength);for(int I=0;I<8;I++)C.GetBool(TEXT("Layers"),*FString::FromInt(I),P.Layers[I]);C.GetBool(TEXT("State"),TEXT("Compact"),State.Compact);C.GetBool(TEXT("State"),TEXT("Pinned"),State.Pinned);C.GetBool(TEXT("State"),TEXT("AutoCollapse"),State.AutoCollapse);ReadMotion(C,TEXT("Motion"));Events.Empty();Notice=TEXT("Presentation loaded  /  preview rewards reset");}
 void Activate(int Id){if(Id<0)return;if(Id>=1100&&Id<1100+ParamCount){Remember();int I=Id-1100;float V=GetParam(KitScope?Draft:P,I);if(V>0){ModuleRecall[I]=V;EditParameter(I,0);}else EditParameter(I,ModuleRecall[I]>0?ModuleRecall[I]:1);return;}if(Id>=900&&Id<900+ParamCount){Commit();Remember();Edit=Id;Buffer=FString::SanitizeFloat(GetParam(KitScope?Draft:P,Id-900));Replace=true;return;}if(Id>=800&&Id<800+ParamCount){Remember();int I=Id-800;float V=GetParam(KitScope?Draft:P,I)+1;if(V>Params[I].Max)V=Params[I].Min;EditParameter(I,V);return;}if(Id==78){Undo(false);return;}if(Id==79){Undo(true);return;}if(Id>=100&&Id<=104){Commit();Edit=Id;Buffer=Id==100?D.Name:Id==101?FString::FromInt(D.Level):Id==102?FString::FromInt(D.XP):Id==103?FString::FromInt(D.MaxXP):PresetName;Replace=true;return;}Commit();
 if(Id==60){KitScope=false;if(Tab==2)Category=4;if(Tab==1&&Category==4)Category=0;Notice=TEXT("Components / edit the profile and test its behavior");}
 if(Id==61){KitScope=true;RefreshNames();Notice=TEXT("UI Kit / shared resources with per-value local overrides");}
 if(Id>=70&&Id<76){SelectCategory(Id-70);}
 if(Id==76)ControlPage=FMath::Max(0,ControlPage-1);if(Id==77){int N=0;for(auto Param:Params)if(Param.Category==Category)N++;ControlPage=FMath::Min((N-1)/6,ControlPage+1);}
 if(Id==69){Remember();ApplyDraft();}
 if(Id==80){PresetName=SafePresetName(PresetName.Left(19)+TEXT(" copy"));KitDirty[Category]=true;Notice=TEXT("New preset draft / edit name then Save preset");}
 if(Id==81){SoloBar=!SoloBar;Category=5;Tab=2;ControlPage=0;}
 if(Id==67)PresetPage=FMath::Max(0,PresetPage-1);if(Id==68)PresetPage=FMath::Min(FMath::Max(0,(PresetNames.Num()-1)/6),PresetPage+1);
 if(Id==62){K.PulseAt=K.Time;K.Playing=true;}
 if(Id==63)AddXP(150);
 if(Id==64)SaveKitPreset();
 if(Id==65)BrowseKitPreset(PresetName);
 if(Id==66){Remember();for(int I=0;I<ParamCount;I++)if(Params[I].Category==Category)Overrides[I]=false;ResolveKit();Notice=TEXT("Category restored to shared values");}
 if(Id>=500&&Id<500+ParamCount){Remember();Overrides[Id-500]=false;ResolveKit();}
 if(Id>=600&&Id<600+PresetNames.Num()){Remember();BrowseKitPreset(PresetNames[Id-600]);}
 if(Id==1)Save();if(Id==2){Load();LoadKit();}if(Id==3)FGenericPlatformMisc::RequestExit(false);if(Id>=10&&Id<=12){Tab=Id-10;ControlPage=0;if(Tab==1)SelectCategory(0);if(Tab==2)SelectCategory(4);RefreshNames();}if(Id==20){K.Playing=!K.Playing;}if(Id==21){SeekEnd=12;State.LayoutFrom=State.Compact?1.f:0.f;State.LayoutAt=-10;K.Time=0;K.Transition=0;K.From=0;K.Exiting=false;K.Playing=false;}if(Id==22)BeginTransition(false);if(Id==23)BeginTransition(true);if(Id==24){K.PulseAt=-100;SeekEnd=12;State.LayoutFrom=State.Compact?1.f:0.f;State.LayoutAt=-10;Notice=TEXT("Preview restarted / synthetic rewards cleared");Events.Empty();K.Time=0;K.Transition=0;K.From=0;K.Exiting=false;K.Playing=true;}if(Id==30)State.SetCompact(false,K.Time,!K.Playing);if(Id==31)State.SetCompact(true,K.Time,!K.Playing);if(Id==32){State.Pinned=!State.Pinned;if(State.Pinned)State.SetCompact(false,K.Time,!K.Playing);}if(Id==33)State.Disabled=!State.Disabled;if(Id==34)State.AutoCollapse=!State.AutoCollapse;if(Id==40)AddXP(50);if(Id==41)AddXP(100);if(Id==42){D.XP=D.MaxXP-50;Events.Empty();Notice=TEXT("Threshold fixture: next +100 XP crosses a level");}if(Id==43){Events.Empty();Notice=TEXT("Synthetic events cleared; base profile restored");}if(Id==50)P.Portrait=(P.Portrait+1)%2;if(Id>=200&&Id<208){Remember();P.Layers[Id-200]=!P.Layers[Id-200];}UE_LOG(LogTemp,Display,TEXT("UI_ACTION %d"),Id);}
 void Commit(){if(Edit<0)return;if(Edit>=900&&Edit<900+ParamCount){EditParameter(Edit-900,FCString::Atof(*Buffer));Edit=-1;return;}if(Edit==100)D.Name=Buffer.IsEmpty()?TEXT("OPERATOR"):Buffer.Left(18);if(Edit==101)D.Level=FMath::Clamp(FCString::Atoi(*Buffer),1,999);if(Edit==102){D.XP=FMath::Clamp(FCString::Atoi(*Buffer),0,D.MaxXP-1);Events.Empty();}if(Edit==103){D.MaxXP=FMath::Clamp(FCString::Atoi(*Buffer),100,999999);D.XP=FMath::Min(D.XP,D.MaxXP-1);Events.Empty();}if(Edit==104)PresetName=Buffer.IsEmpty()?TEXT("My motion"):Buffer.Left(24);Edit=-1;}
 FVector2D Position(const FGeometry& G,const FPointerEvent& E)const{float S=FMath::Min(G.GetLocalSize().X/1920.f,G.GetLocalSize().Y/1080.f);return (G.AbsoluteToLocal(E.GetScreenSpacePosition())-(G.GetLocalSize()-FVector2D(1920,1080)*S)*.5f)/S;}
 int HitAt(FVector2D Pnt)const{for(int I=Hits.Num()-1;I>=0;I--)if(Hits[I].Rect.ContainsPoint(Pnt))return Hits[I].Id;return -1;}
 void Slide(int Id,FVector2D Pnt){for(auto H:Hits)if(H.Id==Id){float T=Sat((Pnt.X-H.Rect.Left)/(H.Rect.Right-H.Rect.Left));if(Id>=400&&Id<400+ParamCount){int I=Id-400;EditParameter(I,FMath::Lerp(Params[I].Min,Params[I].Max,T));}if(Id==300){K.Time=T*SeekEnd;K.Playing=false;}}}
 FReply OnMouseMove(const FGeometry& G,const FPointerEvent& E)override{auto Pos=Position(G,E);Hover=HitAt(Pos);if(Dragging>=300&&Dragging<500)Slide(Dragging,Pos);State.Hover=!State.Disabled&&FSlateRect(340,300,1370,610).ContainsPoint(Pos);if(State.Hover&&State.AutoCollapse)State.SetCompact(false,K.Time,!K.Playing);return FReply::Handled();}
 void OnMouseLeave(const FPointerEvent& E)override{State.Hover=false;Hover=-1;SLeafWidget::OnMouseLeave(E);}
 FReply OnMouseButtonDown(const FGeometry& G,const FPointerEvent& E)override{if(E.GetEffectingButton()!=EKeys::LeftMouseButton)return FReply::Unhandled();auto Pos=Position(G,E);int Id=HitAt(Pos);if((Id>=300&&Id<500)){Commit();Remember();Dragging=Id;Slide(Id,Pos);return FReply::Handled().CaptureMouse(SharedThis(this)).SetUserFocus(SharedThis(this));}Activate(Id);return FReply::Handled().SetUserFocus(SharedThis(this));}
 FReply OnMouseButtonUp(const FGeometry&,const FPointerEvent&)override{Dragging=-1;return FReply::Handled().ReleaseMouseCapture();}
 FReply OnKeyChar(const FGeometry&,const FCharacterEvent& E)override{TCHAR Ch=E.GetCharacter();if(Edit>=0&&Ch>=32&&Ch!=127){if(Edit>=101&&Edit<=103&&!FChar::IsDigit(Ch))return FReply::Handled();if(Replace){Buffer.Empty();Replace=false;}if(Buffer.Len()<((Edit==100)?18:(Edit==104?24:12)))Buffer.AppendChar(Ch);return FReply::Handled();}return FReply::Unhandled();}
 FReply OnKeyDown(const FGeometry&,const FKeyEvent& E)override{auto Key=E.GetKey();if(Edit>=0){if(Key==EKeys::V&&E.IsControlDown()){FString Paste;FPlatformApplicationMisc::ClipboardPaste(Paste);if(Replace)Buffer.Empty();for(TCHAR Ch:Paste){if(Ch>=32&&Ch!=127&&(!(Edit>=101&&Edit<=103)||FChar::IsDigit(Ch)))Buffer.AppendChar(Ch);}Buffer=Buffer.Left(Edit==100?18:Edit==104?24:12);Replace=false;}else if(Key==EKeys::Enter)Commit();else if(Key==EKeys::Escape)Edit=-1;else if(Key==EKeys::BackSpace){if(Replace)Buffer.Empty();else Buffer=Buffer.LeftChop(1);Replace=false;}else if(Key==EKeys::A&&E.IsControlDown())Replace=true;else if(Key==EKeys::Tab){Commit();}return FReply::Handled();}if(Key==EKeys::Z&&E.IsControlDown())Undo(false);else if(Key==EKeys::Y&&E.IsControlDown())Undo(true);else if(Key==EKeys::SpaceBar)Activate(20);else if(Key==EKeys::R)Activate(24);else if(Key==EKeys::E)Activate(22);else if(Key==EKeys::X)Activate(23);else if(Key==EKeys::F11){if(auto PC=World->GetFirstPlayerController())PC->ConsoleCommand(TEXT("togglefullscreen"));}else if(Key==EKeys::S&&E.IsControlDown())Save();else if(Key==EKeys::F9)Shot(TEXT("Manual.png"));else return FReply::Unhandled();return FReply::Handled();}
 void Region(int Id,float X,float Y,float W,float H)const{Hits.Add({Id,FSlateRect(X,Y,X+W,Y+H)});}
 void Button(Canvas& C,int Id,float X,float Y,float W,float H,const FString& Label,bool Active=false)const{bool Hot=Hover==Id;C.Cut(X,Y,W,H,Active?FLinearColor(.01f,.11f,.17f):Hot?FLinearColor(.025f,.065f,.09f):Panel,Active?A(Cyan,.85f):Hot?Muted:Line,4);if(Active)C.Box(X,Y+5,2,H-10,Cyan);C.Text(X+12,Y+(H-18)/2,Label,11,Active||Hot?White:Muted);Region(Id,X,Y,W,H);}
 void Field(Canvas& C,int Id,float Y,const FString& Label,const FString& Value)const{C.Text(1454,Y+10,Label,12,Muted);C.Cut(1613,Y,253,38,Ink,Edit==Id?Cyan:Line,3);FString Display=Edit==Id?Buffer+TEXT("|"):Value;int Size=12;auto Measure=FSlateApplication::Get().GetRenderer()->GetFontMeasureService();while(Size>8&&Measure->Measure(Display,FSlateFontInfo(Canvas::Font(false),Size)).X>229)--Size;C.Clip(1622,Y+3,236,33);C.Text(1625,Y+9,Display,Size,White);C.Unclip();Region(Id,1613,Y,253,38);}
 void Section(Canvas& C,float Y,const FString& Label)const{C.Text(1454,Y,Label,12,White,true);C.Seg(1454,Y+29,1866,Y+29,Line);}

#include "WorkbenchView.inl"
 void Shot(const FString& Name){IFileManager::Get().MakeDirectory(*Evidence,true);FScreenshotRequest::RequestScreenshot(Evidence/Name,true,false);}
 void ExecuteQA(FString Cmd){Cmd.TrimStartAndEndInline();TArray<FString>A;Cmd.ParseIntoArrayWS(A);if(A.Num()==0)return;if(A[0]==TEXT("action")&&A.Num()>1)Activate(FCString::Atoi(*A[1]));if(A[0]==TEXT("seek")&&A.Num()>1){K.Time=FCString::Atof(*A[1]);K.Playing=false;}if(A[0]==TEXT("shot")&&A.Num()>1)Shot(A[1]);if(A[0]==TEXT("field")&&A.Num()>2){Activate(FCString::Atoi(*A[1]));Buffer=Cmd.Mid(Cmd.Find(A[2]));Commit();}if(A[0]==TEXT("slider")&&A.Num()>2){int Id=FCString::Atoi(*A[1]);for(auto H:Hits)if(H.Id==Id)Slide(Id,{FMath::Lerp(H.Rect.Left,H.Rect.Right,Sat(FCString::Atof(*A[2]))),H.Rect.Top});}if(A[0]==TEXT("param")&&A.Num()>2){EditParameter(FCString::Atoi(*A[1]),FCString::Atof(*A[2]));}if(A[0]==TEXT("browse")&&A.Num()>1)BrowseKitPreset(Cmd.Mid(7));if(A[0]==TEXT("preset")&&A.Num()>1)ApplyKitPreset(Cmd.Mid(7));if(A[0]==TEXT("kit-status")){FString Out;for(int I=0;I<ParamCount;I++)Out+=FString::Printf(TEXT("%s effective=%.4f shared=%.4f override=%d\n"),Params[I].Key,GetParam(P,I),GetParam(Shared,I),Overrides[I]);FFileHelper::SaveStringToFile(Out,*(Evidence/TEXT("kit-status.txt")));}if(A[0]==TEXT("metrics-reset")){FrameSum=0;FrameCount=0;MaxFrame=0;}if(A[0]==TEXT("exit"))FGenericPlatformMisc::RequestExit(false);if(A[0]==TEXT("status")){auto V=Evaluate(D,P,K,Events);FString Status=FString::Printf(TEXT("time=%.4f playing=%d events=%d level=%d xp=%d fill=%.6f compact=%d disabled=%d pinned=%d entry=%d exit=%d FPS=%.2f maxFrameMs=%.2f"),K.Time,K.Playing,Events.Num(),V.Level,V.XP,V.Fill,State.Compact,State.Disabled,State.Pinned,P.Entrance,P.Exit,FrameCount/FMath::Max(.001f,FrameSum),MaxFrame*1000);FFileHelper::SaveStringToFile(Status,*(Evidence/TEXT("status.txt")));}}

#include "KitVerification.inl"
#include "WorkbenchKit.inl"
 void Check(bool Pass,const FString& Label){Checks+=(Pass?TEXT("PASS "):TEXT("FAIL "))+Label+TEXT("\n");UE_LOG(LogTemp,Display,TEXT("WORKBENCH_CHECK %s %s"),Pass?TEXT("PASS"):TEXT("FAIL"),*Label);}
private:
 TWeakObjectPtr<UWorld>World;TArray<TStrongObjectPtr<UTexture2D>>Textures;FSlateBrush Portraits[2];ProfileData D;Presentation P;ProfileState State;Playback K;TArray<Reward>Events;mutable TArray<Hit>Hits;
 TStrongObjectPtr<UMaterialInstanceDynamic> GlassMaterial;FSlateBrush GlassBrush;Presentation Shared,Draft,Drafts[6];FString DraftNames[6];bool Overrides[ParamCount]={};float ModuleRecall[ParamCount]={};bool KitScope=false,KitDirty[6]={};int Category=0,PresetPage=0,ControlPage=0;FString Linked[6];TArray<FString> PresetNames;
 FString DataDir,Notice=TEXT("Ready"),Buffer,PresetName=TEXT("My motion"),Evidence,Checks;int DeferredAction=-1,DeferredFrames=0;int Tab=0,Hover=-1,Edit=-1,Dragging=-1,VerifyStep=0,FrameCount=0;bool SoloBar=false,Replace=false,Verify=false,QA=false,PersistenceRead=false,TitleSet=false;double Started=0;float SeekEnd=12,RealTime=0,FrameSum=0,MaxFrame=0,Frozen=0,FrozenFill=0,LastQA=0;
};
}
AWorkbenchGameMode::AWorkbenchGameMode(){DefaultPawnClass=nullptr;}
void AWorkbenchGameMode::BeginPlay(){Super::BeginPlay();if(GEngine&&GEngine->GameViewport){auto UI=SNew(KW::SWorkbench).World(GetWorld());GEngine->GameViewport->AddViewportWidgetContent(UI,100);if(auto PC=GetWorld()->GetFirstPlayerController()){PC->bShowMouseCursor=true;FInputModeUIOnly Mode;Mode.SetWidgetToFocus(UI);Mode.SetLockMouseToViewportBehavior(EMouseLockMode::DoNotLock);PC->SetInputMode(Mode);}if(auto Window=GEngine->GameViewport->GetWindow())Window->SetTitle(FText::FromString(TEXT("KOALITIC | UI Workbench 0.3")));FSlateApplication::Get().SetKeyboardFocus(UI);}}











