// Shared resources are edited as drafts. Browsing never changes component bindings.
Presentation PreviewValues()const{Presentation V=P;if(Nav.KitScope)for(int I=0;I<ParamCount;I++)if(Params[I].Category==Nav.Category)SetParam(V,I,GetParam(Draft,I));return V;}
struct ResourceDraft {Presentation Values;bool Dirty=false;};
FString ResourceDraftKey(int Category,const FString& Name)const{return FString::Printf(TEXT("%d/%s"),Category,*Name);}
void StoreCurrentDraft(){FString Key=ResourceDraftKey(Nav.Category,PresetName);if(KitDirty[Nav.Category])ResourceDrafts.Add(Key,{Draft,true});else ResourceDrafts.Remove(Key);}
void SelectCategory(int Next){StoreCurrentDraft();Drafts[Nav.Category]=Draft;DraftNames[Nav.Category]=PresetName;Nav.SelectCategory(Next);Draft=Drafts[Nav.Category];PresetName=DraftNames[Nav.Category];PresetPicker=false;RefreshNames();}
void ResolveKit(){KitBindings::Resolve(P,Shared,Overrides);}
void CaptureVariant(){if(!Variants.IsValidIndex(ActiveVariant))return;auto& V=Variants[ActiveVariant];V.Local=P;for(int I=0;I<ParamCount;I++)V.Overrides[I]=Overrides[I];for(int Cat=0;Cat<7;Cat++)V.Links[Cat]=Linked[Cat];}
void RestoreVariant(int Index){if(!Variants.IsValidIndex(Index))return;ActiveVariant=Index;const auto& V=Variants[Index];P=V.Local;for(int I=0;I<ParamCount;I++)Overrides[I]=V.Overrides[I]||Params[I].Category==5;Shared=Presentation();KitPresetStore Store(DataDir);for(int Cat=0;Cat<7;Cat++){Linked[Cat]=V.Links[Cat];Store.Load(Cat,Linked[Cat],Shared);}ResolveKit();RefreshNames();UndoStack.Empty();RedoStack.Empty();Notice=FString::Printf(TEXT("Design variant %d / %s"),Index+1,*V.Name);}
void LoadVariants(){FConfigFile C;C.Read(DataDir/TEXT("Presentation.ini"));if(ProfileVariantStore::Read(C,KitPresetStore(DataDir),Variants,ActiveVariant)){RestoreVariant(ActiveVariant);}else{Variants.Reset();Variants.Add(ProfileVariant());ActiveVariant=0;CaptureVariant();}ComponentDirty=false;}
void SwitchVariant(int Index){if(!Variants.IsValidIndex(Index)||Index==ActiveVariant)return;CaptureVariant();RestoreVariant(Index);PresetPicker=false;}
void CreateVariant(){if(Variants.Num()>=12){Notice=TEXT("Maximum of 12 design variants");return;}CaptureVariant();ProfileVariant New=Variants[ActiveVariant];New.Name=FString::Printf(TEXT("Variant %02d"),Variants.Num()+1);Variants.Add(New);RestoreVariant(Variants.Num()-1);ComponentDirty=true;Notice=TEXT("New visual variant / shared profile data / Save component to keep it");}
void EditParameter(int I,float Value){if(Nav.KitScope){SetParam(Draft,I,Value);if(I>=EffectExtraBase+FrameHue&&I<=EffectExtraBase+LevelOpacity)Draft.Extra[ThemeCustom]=1;KitDirty[Nav.Category]=true;}else{KitBindings::SetLocal(P,Overrides,I,Value);if(I>=EffectExtraBase+FrameHue&&I<=EffectExtraBase+LevelOpacity){P.Extra[ThemeCustom]=1;Overrides[EffectExtraBase+ThemeCustom]=true;}ComponentDirty=true;}ResolveKit();}
struct EditSnapshot {Presentation Local,Global,DraftValues;Presentation CategoryDrafts[7];TArray<bool> Flags;TArray<FString> Links;TMap<FString,ResourceDraft> ResourceDrafts;FString CategoryNames[7],Name;bool Dirty[7];int SelectedCategory=0;};
TArray<EditSnapshot> UndoStack,RedoStack;
EditSnapshot Snapshot()const{EditSnapshot S;S.Local=P;S.Global=Shared;S.DraftValues=Draft;S.Name=PresetName;S.SelectedCategory=Nav.Category;S.ResourceDrafts=ResourceDrafts;for(int I=0;I<ParamCount;I++)S.Flags.Add(Overrides[I]);for(int I=0;I<7;I++){S.Links.Add(Linked[I]);S.CategoryDrafts[I]=Drafts[I];S.CategoryNames[I]=DraftNames[I];S.Dirty[I]=KitDirty[I];}return S;}
void Remember(){UndoStack.Add(Snapshot());if(UndoStack.Num()>50)UndoStack.RemoveAt(0);RedoStack.Empty();}
void RestoreSnapshot(const EditSnapshot& S){P=S.Local;Shared=S.Global;Draft=S.DraftValues;PresetName=S.Name;ResourceDrafts=S.ResourceDrafts;Nav.SelectCategory(S.SelectedCategory);for(int I=0;I<ParamCount;I++)Overrides[I]=S.Flags[I];for(int I=0;I<7;I++){Linked[I]=S.Links[I];Drafts[I]=S.CategoryDrafts[I];DraftNames[I]=S.CategoryNames[I];KitDirty[I]=S.Dirty[I];}ResolveKit();RefreshNames();}
void Undo(bool Redo){auto& From=Redo?RedoStack:UndoStack;auto& To=Redo?UndoStack:RedoStack;if(From.IsEmpty())return;To.Add(Snapshot());auto S=From.Pop();RestoreSnapshot(S);Notice=Redo?TEXT("Edit restored / save explicitly to keep changes"):TEXT("Edit undone / saved library files unchanged");}
void RefreshNames(){Nav.PresetPage=0;PickerOffset=0;PresetNames=KitPresetStore(DataDir).Names(Nav.Category);if(!PresetNames.Contains(Linked[Nav.Category]))PresetNames.Add(Linked[Nav.Category]);PresetNames.Sort();}
FString SafePresetName(FString Name){return KitPresetStore::SafeName(Name);}
void SaveKitPreset(){Commit();PresetName=SafePresetName(PresetName);if(KitPresetStore(DataDir).Save(Nav.Category,PresetName,Draft)){if(Linked[Nav.Category]==PresetName){for(int I=0;I<ParamCount;I++)if(Params[I].Category==Nav.Category)SetParam(Shared,I,GetParam(Draft,I));ResolveKit();}ResourceDrafts.Remove(ResourceDraftKey(Nav.Category,PresetName));KitDirty[Nav.Category]=false;Drafts[Nav.Category]=Draft;DraftNames[Nav.Category]=PresetName;RefreshNames();Notice=TEXT("Preset saved / matching links update; component is not saved automatically");}else Notice=TEXT("PRESET SAVE FAILED");}
void BrowseKitPreset(const FString& Name,bool DiscardCurrent=false){if(DiscardCurrent){ResourceDrafts.Remove(ResourceDraftKey(Nav.Category,PresetName));KitDirty[Nav.Category]=false;}else StoreCurrentDraft();Presentation Candidate;bool Dirty=false;if(const ResourceDraft* Cached=ResourceDrafts.Find(ResourceDraftKey(Nav.Category,Name))){Candidate=Cached->Values;Dirty=Cached->Dirty;}else if(!KitPresetStore(DataDir).Load(Nav.Category,Name,Candidate)){Notice=TEXT("Preset not found / current draft unchanged");return;}Draft=Candidate;PresetName=Name;KitDirty[Nav.Category]=Dirty;Drafts[Nav.Category]=Draft;DraftNames[Nav.Category]=PresetName;Notice=Dirty?TEXT("Unsaved draft restored / save when ready"):TEXT("Preset selected / component links unchanged");}
void ApplyDraft(){if(KitDirty[Nav.Category]){Notice=TEXT("Save this preset before applying its shared link");return;}for(int I=0;I<ParamCount;I++)if(Params[I].Category==Nav.Category)SetParam(Shared,I,GetParam(Draft,I));Linked[Nav.Category]=PresetName;ResolveKit();ComponentDirty=true;Notice=TEXT("Preset linked / local overrides preserved / Save component to keep link");}
void LinkComponentPreset(const FString& Name){if(Nav.Category==5)return;Presentation Candidate;if(!KitPresetStore(DataDir).Load(Nav.Category,Name,Candidate)){Notice=TEXT("Preset not found / link unchanged");return;}for(int I=0;I<ParamCount;I++)if(Params[I].Category==Nav.Category)SetParam(Shared,I,GetParam(Candidate,I));Linked[Nav.Category]=Name;ResolveKit();ComponentDirty=true;Notice=TEXT("Preset linked / Save component to keep the assignment");}
void ApplyKitPreset(const FString& Name){if(!KitPresetStore(DataDir).Names(Nav.Category).Contains(Name)){Notice=TEXT("Preset not found / link unchanged");return;}BrowseKitPreset(Name);ApplyDraft();}
void WriteKitLinks(FConfigFile& C){KitBindings::Write(C,P,Overrides,Linked);}
void LoadKit(){FConfigFile C;C.Read(DataDir/TEXT("Presentation.ini"));KitBindings::Read(C,KitPresetStore(DataDir),P,Shared,Overrides,Linked);for(int I=0;I<ParamCount;I++)if(Params[I].Category==5)Overrides[I]=true;ResourceDrafts.Empty();for(int Cat=0;Cat<7;Cat++){KitDirty[Cat]=false;Drafts[Cat]=Shared;DraftNames[Cat]=Linked[Cat];}Draft=Shared;PresetName=Linked[Nav.Category];RefreshNames();}
void SeedKit(){if(!KitPresetStore(DataDir).Seed(Linked))Notice=TEXT("UI Kit defaults could not be saved");RefreshNames();}
void NavigateSection(int Section){
 if(Section==1||Section==2)Section=0; // The former Components destination is the Library selection.
 if(Nav.Section==Section){if(Section==0)Nav.DrawerOpen=!Nav.DrawerOpen;PresetPicker=false;return;}
 Nav.DrawerOpen=Section==0;
 if(Section==0){
  if(Nav.KitScope){StoreCurrentDraft();Drafts[Nav.Category]=Draft;DraftNames[Nav.Category]=PresetName;Nav.OpenComponents();Draft=Drafts[Nav.Category];PresetName=DraftNames[Nav.Category];}
  Nav.SelectSection(Section);Nav.SelectInspector(0);Nav.SelectedLayer=-1;
 }else{
  if(!Nav.KitScope){Nav.OpenKit();Draft=Drafts[Nav.Category];PresetName=DraftNames[Nav.Category];}
  Nav.SelectSection(Section);SelectCategory(Section==3?4:Section==4?0:Section==5?2:Section==6?3:6);
 }
 PresetPicker=false;RefreshNames();
}
void DeleteCurrentPreset(){
 if(!Nav.KitScope)return;
 CaptureVariant();
 for(const auto& Variant:Variants)if(Variant.Links[Nav.Category]==PresetName){Notice=TEXT("Preset is linked to a layout / choose a replacement there before deleting");DeleteArmed=false;return;}
 if(Linked[Nav.Category]==PresetName){Notice=TEXT("Preset is linked to the active layout / replace its link first");DeleteArmed=false;return;}
 TArray<FString> Available=KitPresetStore(DataDir).Names(Nav.Category);if(Available.Num()<2){Notice=TEXT("Keep at least one preset in each resource category");DeleteArmed=false;return;}
 if(!DeleteArmed){DeleteArmed=true;Notice=TEXT("Click Confirm delete again to remove this unused preset");return;}
 if(!KitPresetStore(DataDir).Delete(Nav.Category,PresetName)){Notice=TEXT("Preset deletion failed");DeleteArmed=false;return;}
 FString Removed=PresetName;ResourceDrafts.Remove(ResourceDraftKey(Nav.Category,Removed));DeleteArmed=false;RefreshNames();BrowseKitPreset(PresetNames[0],true);Notice=FString::Printf(TEXT("Deleted preset %s / selected %s"),*Removed,*PresetName);
}
void KitControls(Canvas& C,float Top,float Bottom)const{DrawKitParameterEditor(C,Top,Bottom,Nav.KitScope?Nav.KitScroll[Nav.Category]:Nav.ComponentScroll[Nav.Category],Nav.KitScope?Draft:P,Nav.Category,Nav.KitScope||Nav.Category==5,Overrides,Edit,Buffer,
 [this,&C](int Id,float X,float Y,float W,float H,const FString& Label,bool Active){Button(C,Id,X,Y,W,H,Label,Active,CategoryColor(Nav.Category));},
 [this](int Id,float X,float Y,float W,float H){Region(Id,X,Y,W,H);});}
void UpdateMaterial(){if(!GlassMaterial.IsValid())return;Presentation Q=PreviewValues();auto* M=GlassMaterial.Get();auto V=Evaluate(PreviewProfile(),Q,K,Events);M->SetScalarParameterValue(TEXT("Clock"),K.Time);M->SetScalarParameterValue(TEXT("Strength"),Q.Ambient&&!State.Disabled?Q.AmbientStrength:0);M->SetScalarParameterValue(TEXT("Speed"),Q.Speed);M->SetScalarParameterValue(TEXT("GlassSpeed"),Q.Extra[GlassSpeed]);M->SetScalarParameterValue(TEXT("ParticleSpeed"),Q.Extra[ParticleSpeed]);M->SetScalarParameterValue(TEXT("PerimeterSpeed"),Q.Extra[PerimeterSpeed]);M->SetScalarParameterValue(TEXT("Sweep"),Q.Sweep);M->SetScalarParameterValue(TEXT("Particles"),Q.Layers[7]?Q.Particles:0);M->SetScalarParameterValue(TEXT("Glow"),Q.Layers[6]?Q.Glow:0);M->SetScalarParameterValue(TEXT("Compact"),State.Layout(K.Time));M->SetScalarParameterValue(TEXT("Mode"),Q.AmbientMode);M->SetScalarParameterValue(TEXT("Scan"),Q.Scan);M->SetScalarParameterValue(TEXT("Perimeter"),Q.Perimeter);M->SetScalarParameterValue(TEXT("Design"),Q.Design);M->SetScalarParameterValue(TEXT("ParticleSize"),Q.ParticleSize);M->SetScalarParameterValue(TEXT("ParticleDrift"),Q.ParticleDrift);M->SetScalarParameterValue(TEXT("Reaction"),State.Disabled||!Q.Layers[7]?0:FMath::Max((K.Time>=K.PulseAt?Sat(1-(K.Time-K.PulseAt)/Q.ReactionDuration):0.f)*Q.Reaction,Sat(1-V.RewardAge/Q.Extra[EventDuration])*Q.Extra[EventIntensity]));}
