// Shared resources are edited as drafts. Browsing never changes component bindings.
Presentation PreviewValues()const{Presentation V=P;if(KitScope)for(int I=0;I<ParamCount;I++)if(Params[I].Category==Category)SetParam(V,I,GetParam(Draft,I));return V;}
void SelectCategory(int Next){Drafts[Category]=Draft;DraftNames[Category]=PresetName;Category=Next;ControlPage=0;Draft=Drafts[Category];PresetName=DraftNames[Category];RefreshNames();}
void ResolveKit(){KitBindings::Resolve(P,Shared,Overrides);}
void EditParameter(int I,float Value){if(KitScope){SetParam(Draft,I,Value);KitDirty[Category]=true;}else KitBindings::SetLocal(P,Overrides,I,Value);ResolveKit();}
struct EditSnapshot {Presentation Local,Global,DraftValues;Presentation CategoryDrafts[6];TArray<bool> Flags;TArray<FString> Links;FString CategoryNames[6],Name;bool Dirty[6];int SelectedCategory=0;};
TArray<EditSnapshot> UndoStack,RedoStack;
EditSnapshot Snapshot()const{EditSnapshot S;S.Local=P;S.Global=Shared;S.DraftValues=Draft;S.Name=PresetName;S.SelectedCategory=Category;for(int I=0;I<ParamCount;I++)S.Flags.Add(Overrides[I]);for(int I=0;I<6;I++){S.Links.Add(Linked[I]);S.CategoryDrafts[I]=Drafts[I];S.CategoryNames[I]=DraftNames[I];S.Dirty[I]=KitDirty[I];}return S;}
void Remember(){UndoStack.Add(Snapshot());if(UndoStack.Num()>50)UndoStack.RemoveAt(0);RedoStack.Empty();}
void RestoreSnapshot(const EditSnapshot& S){P=S.Local;Shared=S.Global;Draft=S.DraftValues;PresetName=S.Name;Category=S.SelectedCategory;for(int I=0;I<ParamCount;I++)Overrides[I]=S.Flags[I];for(int I=0;I<6;I++){Linked[I]=S.Links[I];Drafts[I]=S.CategoryDrafts[I];DraftNames[I]=S.CategoryNames[I];KitDirty[I]=S.Dirty[I];}ResolveKit();RefreshNames();}
void Undo(bool Redo){auto& From=Redo?RedoStack:UndoStack;auto& To=Redo?UndoStack:RedoStack;if(From.IsEmpty())return;To.Add(Snapshot());auto S=From.Pop();RestoreSnapshot(S);Notice=Redo?TEXT("Edit restored / save explicitly to keep changes"):TEXT("Edit undone / saved library files unchanged");}
void RefreshNames(){PresetPage=0;PresetNames=KitPresetStore(DataDir).Names(Category);if(!PresetNames.Contains(Linked[Category]))PresetNames.Add(Linked[Category]);PresetNames.Sort();}
FString SafePresetName(FString Name){return KitPresetStore::SafeName(Name);}
void SaveKitPreset(){Commit();PresetName=SafePresetName(PresetName);if(KitPresetStore(DataDir).Save(Category,PresetName,Draft)){if(Linked[Category]==PresetName){for(int I=0;I<ParamCount;I++)if(Params[I].Category==Category)SetParam(Shared,I,GetParam(Draft,I));ResolveKit();}KitDirty[Category]=false;RefreshNames();Notice=TEXT("Preset saved / matching links update; component is not saved automatically");}else Notice=TEXT("PRESET SAVE FAILED");}
void BrowseKitPreset(const FString& Name){Presentation Candidate=Shared;if(!KitPresetStore(DataDir).Load(Category,Name,Candidate)){Notice=TEXT("Preset not found / current draft unchanged");return;}Draft=Candidate;PresetName=Name;KitDirty[Category]=false;Notice=TEXT("Audition only / Apply links this preset; local overrides remain");}
void ApplyDraft(){if(KitDirty[Category]){Notice=TEXT("Save this preset before applying its shared link");return;}for(int I=0;I<ParamCount;I++)if(Params[I].Category==Category)SetParam(Shared,I,GetParam(Draft,I));Linked[Category]=PresetName;ResolveKit();Notice=TEXT("Preset applied / local overrides preserved / Save component to keep link");}
void ApplyKitPreset(const FString& Name){if(!KitPresetStore(DataDir).Names(Category).Contains(Name)){Notice=TEXT("Preset not found / link unchanged");return;}BrowseKitPreset(Name);ApplyDraft();}
void WriteKitLinks(FConfigFile& C){KitBindings::Write(C,P,Overrides,Linked);}
void LoadKit(){FConfigFile C;C.Read(DataDir/TEXT("Presentation.ini"));KitBindings::Read(C,KitPresetStore(DataDir),P,Shared,Overrides,Linked);for(int Cat=0;Cat<6;Cat++){KitDirty[Cat]=false;Drafts[Cat]=Shared;DraftNames[Cat]=Linked[Cat];}Draft=Shared;PresetName=Linked[Category];RefreshNames();}
void SeedKit(){if(!KitPresetStore(DataDir).Seed(Linked))Notice=TEXT("UI Kit defaults could not be saved");RefreshNames();}
void KitControls(Canvas& C,float Top)const{DrawKitParameterEditor(C,Top,KitScope?Draft:P,Category,ControlPage,KitScope,Overrides,Edit,Buffer,
 [this,&C](int Id,float X,float Y,float W,float H,const FString& Label,bool Active){Button(C,Id,X,Y,W,H,Label,Active);},
 [this](int Id,float X,float Y,float W,float H){Region(Id,X,Y,W,H);});}
void UpdateMaterial(){if(!GlassMaterial.IsValid())return;Presentation Q=PreviewValues();auto* M=GlassMaterial.Get();auto V=Evaluate(D,Q,K,Events);M->SetScalarParameterValue(TEXT("Clock"),K.Time);M->SetScalarParameterValue(TEXT("Strength"),Q.Ambient&&!State.Disabled?Q.AmbientStrength:0);M->SetScalarParameterValue(TEXT("Speed"),Q.Speed);M->SetScalarParameterValue(TEXT("Sweep"),Q.Sweep);M->SetScalarParameterValue(TEXT("Particles"),Q.Layers[7]?Q.Particles:0);M->SetScalarParameterValue(TEXT("Glow"),Q.Layers[6]?Q.Glow:0);M->SetScalarParameterValue(TEXT("Compact"),State.Layout(K.Time));M->SetScalarParameterValue(TEXT("Mode"),Q.AmbientMode);M->SetScalarParameterValue(TEXT("Scan"),Q.Scan);M->SetScalarParameterValue(TEXT("Perimeter"),Q.Perimeter);M->SetScalarParameterValue(TEXT("Design"),Q.Design);M->SetScalarParameterValue(TEXT("ParticleSize"),Q.ParticleSize);M->SetScalarParameterValue(TEXT("ParticleDrift"),Q.ParticleDrift);M->SetScalarParameterValue(TEXT("Reaction"),State.Disabled||!Q.Layers[7]?0:FMath::Max((K.Time>=K.PulseAt?Sat(1-(K.Time-K.PulseAt)/Q.ReactionDuration):0.f),Sat(1-V.RewardAge/Q.ReactionDuration))*Q.Reaction);}
